import type { GenerationTask } from "./types";

const NOW = Date.now();
const secondsAgo = (s: number) => NOW - s * 1_000;
const minutesAgo = (m: number) => NOW - m * 60_000;
const hoursAgo = (h: number) => NOW - h * 3_600_000;

export const SEED_TASKS: GenerationTask[] = [
  // running (2 — оба слота заняты)
  {
    id: "task-01",
    type: "video",
    modelName: "Veo 3",
    prompt: "Дрон-облёт ночного города, неоновые отражения в лужах, киношный свет",
    status: "running",
    progress: 37,
    createdAt: secondsAgo(200),
    credits: 120,
    etaSec: 42,
  },
  {
    id: "task-02",
    type: "image",
    modelName: "Midjourney v7",
    prompt: "Кинематографичный портрет воина на закате, песчаная буря, золотой свет",
    status: "running",
    progress: 68,
    createdAt: secondsAgo(170),
    credits: 45,
    etaSec: 11,
  },

  // queued (FIFO: task-03 первой)
  {
    id: "task-03",
    type: "text",
    modelName: "Claude Sonnet 4.5",
    prompt: "Объясни простыми словами, что такое квантовая запутанность",
    status: "queued",
    progress: 0,
    createdAt: secondsAgo(150),
    credits: 8,
    etaSec: 6,
  },
  {
    id: "task-04",
    type: "image",
    modelName: "Flux 1.1 Pro",
    prompt: "Минималистичный плакат: оранжевый круг на тёмном фоне, много воздуха",
    status: "queued",
    progress: 0,
    createdAt: secondsAgo(120),
    credits: 25,
    etaSec: 18,
  },
  {
    id: "task-05",
    type: "audio",
    modelName: "Suno v4",
    prompt: "Эмбиент-трек с тёплыми синтезаторами, медленный темп, винил-шум",
    status: "queued",
    progress: 0,
    createdAt: secondsAgo(95),
    credits: 60,
    etaSec: 35,
  },
  {
    id: "task-06",
    type: "video",
    modelName: "Kling 2.5 Turbo",
    prompt: "Капля чернил растворяется в воде, макросъёмка, замедление",
    status: "queued",
    progress: 0,
    createdAt: secondsAgo(80),
    credits: 75,
    etaSec: 50,
  },
  {
    id: "task-07",
    type: "text",
    modelName: "GPT-4o",
    prompt: "Составь план статьи про осознанное потребление для блога",
    status: "queued",
    progress: 0,
    createdAt: secondsAgo(64),
    credits: 7,
    etaSec: 5,
  },
  {
    id: "task-08",
    type: "image",
    modelName: "DAL·E 3",
    prompt: "Изометрическая иллюстрация уютной кофейни в тёплых тонах",
    status: "queued",
    progress: 0,
    createdAt: secondsAgo(48),
    credits: 30,
    etaSec: 20,
  },
  {
    id: "task-09",
    type: "video",
    modelName: "Sora 2",
    prompt: "Замедленная съёмка цветущей сакуры под ветром на рассвете",
    status: "queued",
    progress: 0,
    createdAt: secondsAgo(32),
    credits: 150,
    etaSec: 70,
  },
  {
    id: "task-10",
    type: "audio",
    modelName: "ElevenLabs v3",
    prompt: "Озвучь рекламный ролик мужским голосом, уверенный тон",
    status: "queued",
    progress: 0,
    createdAt: secondsAgo(15),
    credits: 40,
    etaSec: 12,
  },

  // done
  {
    id: "task-11",
    type: "text",
    modelName: "GPT-4o",
    prompt: "Напиши короткое стихотворение про закат над морем",
    status: "done",
    progress: 100,
    createdAt: minutesAgo(22),
    credits: 5,
  },
  {
    id: "task-12",
    type: "image",
    modelName: "Nano Banana",
    prompt: "Архитектура будущего: башня из стекла и меди посреди пустыни",
    status: "done",
    progress: 100,
    createdAt: minutesAgo(34),
    credits: 30,
    durationLabel: "1:1",
  },
  {
    id: "task-13",
    type: "audio",
    modelName: "ElevenLabs v3",
    prompt: "Голос рассказчика читает короткое вступление к подкасту",
    status: "done",
    progress: 100,
    createdAt: minutesAgo(41),
    credits: 40,
    durationLabel: "0:48",
  },
  {
    id: "task-14",
    type: "video",
    modelName: "Runway Gen-3",
    prompt: "Таймлапс распускающегося бутона розы на чёрном фоне",
    status: "done",
    progress: 100,
    createdAt: minutesAgo(55),
    credits: 90,
    durationLabel: "6s",
  },
  {
    id: "task-15",
    type: "text",
    modelName: "Gemini 2.5 Pro",
    prompt: "Слоган для кофейни в стиле минимализма",
    status: "done",
    progress: 100,
    createdAt: minutesAgo(72),
    credits: 6,
  },
  {
    id: "task-16",
    type: "image",
    modelName: "Flux 1.1 Pro",
    prompt: "Акварельный пейзаж туманных гор на рассвете",
    status: "done",
    progress: 100,
    createdAt: hoursAgo(2),
    credits: 25,
    durationLabel: "4:3",
  },
  {
    id: "task-17",
    type: "audio",
    modelName: "Suno v4",
    prompt: "Lo-Fi бит для учёбы, мягкие клавиши, винил-шум",
    status: "done",
    progress: 100,
    createdAt: hoursAgo(3),
    credits: 60,
    durationLabel: "3:12",
  },
  {
    id: "task-18",
    type: "text",
    modelName: "DeepSeek V3",
    prompt: "Переведи техническую документацию на английский, сохрани термины",
    status: "done",
    progress: 100,
    createdAt: hoursAgo(4),
    credits: 9,
  },

  // failed
  {
    id: "task-19",
    type: "video",
    modelName: "Sora 2",
    prompt: "Город ночью с высоты птичьего полёта, длинный плавный пролёт камеры",
    status: "failed",
    progress: 54,
    createdAt: minutesAgo(18),
    credits: 150,
    error: "Превышено время ожидания",
  },
  {
    id: "task-20",
    type: "image",
    modelName: "Midjourney v7",
    prompt: "Гиперреалистичный натюрморт с фруктами при свечах в стиле барокко",
    status: "failed",
    progress: 31,
    createdAt: minutesAgo(38),
    credits: 45,
    error: "Недостаточно кредитов",
  },
  {
    id: "task-21",
    type: "audio",
    modelName: "Udio",
    prompt: "Эпичный оркестровый трек для трейлера, нарастающее напряжение",
    status: "failed",
    progress: 12,
    createdAt: minutesAgo(63),
    credits: 55,
    error: "Модель временно недоступна",
  },
  {
    id: "task-22",
    type: "video",
    modelName: "Pika 1.5",
    prompt: "Анимация логотипа: частицы собираются в букву, мягкое свечение",
    status: "failed",
    progress: 47,
    createdAt: hoursAgo(2),
    credits: 80,
    error: "Превышено время ожидания",
  },
  {
    id: "task-23",
    type: "image",
    modelName: "SDXL",
    prompt: "Концепт-арт инопланетного ландшафта с двумя лунами",
    status: "failed",
    progress: 8,
    createdAt: hoursAgo(5),
    credits: 20,
    error: "Недостаточно кредитов",
  },

  // canceled
  {
    id: "task-24",
    type: "text",
    modelName: "Gemini 2.5 Pro",
    prompt: "Сгенерируй 50 вариантов слогана для кофейни в стиле минимализма",
    status: "canceled",
    progress: 22,
    createdAt: minutesAgo(50),
    credits: 6,
  },
  {
    id: "task-25",
    type: "video",
    modelName: "Kling 2.5 Turbo",
    prompt: "Сёрфер скользит по гигантской волне на закате, замедление",
    status: "canceled",
    progress: 64,
    createdAt: minutesAgo(88),
    credits: 75,
  },
  {
    id: "task-26",
    type: "image",
    modelName: "DAL·E 3",
    prompt: "Ретро-постер космического путешествия в стиле 60-х",
    status: "canceled",
    progress: 5,
    createdAt: hoursAgo(3),
    credits: 30,
  },
  {
    id: "task-27",
    type: "audio",
    modelName: "Suno v4",
    prompt: "Джазовая импровизация на саксофоне, ночное настроение",
    status: "canceled",
    progress: 41,
    createdAt: hoursAgo(6),
    credits: 60,
  },
];
